<?php

return [
    'h1' => 'About «Romashka-М»',
    'paragraphs' => [
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus non elit eu ipsum volutpat congue. Aliquam rutrum id mi id cursus. Nam elementum odio vitae libero mattis porttitor. Maecenas vestibulum in urna vitae ultrices. Nulla massa nisl, vehicula et suscipit a, placerat sed lorem. Duis nec nisl eu metus ultrices pharetra. Donec pellentesque, orci at ornare faucibus, enim sem aliquet dolor, non mollis est mauris vel erat. Nunc hendrerit nisl quis velit sollicitudin tincidunt at vel ante. Sed convallis eros quam, eget sollicitudin orci eleifend eget. Morbi pretium a enim ut dapibus. Vestibulum quis turpis eros. In molestie dui at risus dapibus efficitur. Donec mattis congue libero, vel mollis massa condimentum id. Duis interdum bibendum vehicula.',
        'Sed varius volutpat mauris nec bibendum. Mauris id interdum nunc. Pellentesque dictum turpis erat, ut volutpat libero tempor ut. Proin velit ligula, aliquam vel dui sit amet, convallis facilisis tellus. Phasellus tincidunt quam sit amet sapien bibendum, sed venenatis tellus malesuada. Nam et elementum nisl. Sed vel pulvinar ex. In euismod lorem semper placerat blandit. Donec sed orci ut quam gravida scelerisque ac sit amet leo. Mauris ut dictum purus.',
        'Vivamus placerat eleifend luctus. Duis faucibus hendrerit turpis, eget scelerisque diam accumsan non. Duis erat nisi, dignissim et tempus in, tempor non neque. Curabitur consectetur, erat sit amet porttitor maximus, diam augue mollis lorem, et placerat velit turpis sit amet felis. Quisque scelerisque est turpis, sit amet porttitor est egestas consequat. Proin sed malesuada eros, id congue augue. Nam aliquet condimentum justo, sit amet vestibulum leo efficitur ac. Sed tristique accumsan tempor. Nam non aliquam neque, non semper odio. Vivamus fermentum suscipit ornare. Sed scelerisque, odio vitae bibendum efficitur, lectus enim gravida nibh, sed vehicula dui magna ac tortor. Cras molestie ut nibh in porta. Donec vitae nisl viverra, placerat ligula eu, maximus sem.',
        'Suspendisse malesuada imperdiet congue. Aliquam erat volutpat. Morbi massa turpis, iaculis a diam vitae, dignissim pellentesque mauris. Integer sit amet feugiat tortor, pulvinar posuere eros. Proin porttitor faucibus porta. Etiam consequat ipsum sit amet ex mattis semper. Nullam vel massa ipsum. Nam maximus egestas lacus. Integer eget auctor sem. Cras sed faucibus justo. Vestibulum sit amet odio et nisi molestie efficitur ultricies in eros. Maecenas ac massa et mi feugiat interdum in ut quam.

Sed id ipsum sodales, auctor orci eget, laoreet erat. Maecenas sit amet facilisis leo. Vivamus elementum erat ut velit imperdiet fermentum. Integer dignissim dui vel justo eleifend, nec blandit risus posuere. Curabitur congue laoreet lorem, eget sollicitudin massa accumsan eget. Ut at bibendum metus, non sodales nulla. Quisque quis ipsum id magna gravida egestas. Integer id nisi eu nunc ullamcorper mollis non sit amet elit. Maecenas id sem id tortor convallis lobortis. Maecenas nunc nisi, venenatis id vulputate quis, egestas at mauris. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla at tempor ex, ac pharetra urna.',
    ],


];
